import { useState } from "react";
import { callAI, PROMPTS } from "../lib/ai";

function stripMd(t) {
  return t.replace(/\*\*(.+?)\*\*/g, "$1").replace(/\*(.+?)\*/g, "$1").trim();
}

function Section({ title, items, color }) {
  return (
    <div style={{ marginBottom: 24 }}>
      <div style={{ fontSize: 10, fontWeight: 700, color: color, textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: 12, fontFamily: "system-ui, sans-serif" }}>
        {title}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        {items.map(function(item, i) {
          return (
            <div key={i} style={{ display: "flex", gap: 12, padding: "12px 14px", background: "#FFFFFF", border: "1px solid #E8E6E1", borderRadius: 10, alignItems: "flex-start" }}>
              <div style={{ width: 24, height: 24, borderRadius: 6, background: color, color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, flexShrink: 0, fontFamily: "system-ui, sans-serif" }}>
                {i + 1}
              </div>
              <span style={{ fontSize: 14, lineHeight: 1.7, color: "#1C1C1E", fontFamily: "OpenDyslexic, sans-serif" }}>
                {stripMd(item)}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function parseGuide(text) {
  var result = { concepts: [], questions: [], tricks: [] };
  var current = null;
  var nl = String.fromCharCode(10);
  var lines = text.split(nl);
  for (var i = 0; i < lines.length; i++) {
    var t = lines[i].trim();
    if (t.length === 0) continue;
    var up = t.toUpperCase();
    if (up.indexOf("KEY CONCEPT") !== -1) { current = "concepts"; continue; }
    if (up.indexOf("PRACTICE QUESTION") !== -1) { current = "questions"; continue; }
    if (up.indexOf("MEMORY TRICK") !== -1 || up.indexOf("MNEMONIC") !== -1) { current = "tricks"; continue; }
    if (current === null) continue;
    var cleaned = "";
    if (/^[0-9]+[.):]/.test(t)) { cleaned = t.replace(/^[0-9]+[.):]\s*/, "").trim(); }
    else if (t.charAt(0) === "-" || t.charAt(0) === "*") { cleaned = t.slice(1).trim(); }
    if (cleaned.length > 2) result[current].push(cleaned);
  }
  return result;
}

export default function StudyGuidePanel({ document: docText, ollamaModel, language, onClose }) {
  var [guide,   setGuide]   = useState(null);
  var [loading, setLoading] = useState(false);
  var [error,   setError]   = useState("");
  var [printed, setPrinted] = useState(false);

  var generate = async function() {
    setLoading(true);
    setError("");
    setGuide(null);
    try {
      var result = await callAI({
        ollamaModel: ollamaModel,
        system: PROMPTS.studyGuide(language),
        purpose: 'studyGuide',
        prompt: docText.slice(0, 60000),
      });
      setGuide(parseGuide(result));
    } catch(e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  var handlePrint = function() {
    var contentEl = window.document.getElementById("qt-study-content");
    if (!contentEl) return;
    var style = window.document.createElement("style");
    style.textContent = "@media print { body > *:not(#qt-study-print) { display: none; } }";
    window.document.head.appendChild(style);
    var div = window.document.createElement("div");
    div.id = "qt-study-print";
    div.style.cssText = "font-family:sans-serif;padding:32px;";
    div.innerHTML = contentEl.innerHTML;
    window.document.body.appendChild(div);
    window.print();
    window.document.head.removeChild(style);
    window.document.body.removeChild(div);
    setPrinted(true);
  };

  return (
    <div style={{ fontFamily: "system-ui, sans-serif" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}>
        <div>
          <div style={{ fontSize: 11, fontWeight: 700, color: "#6E6E73", textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: 2 }}>Study Guide</div>
          <div style={{ fontSize: 12, color: "#a88f6b" }}>Generated by Gemma 4 from your document</div>
        </div>
        <button onClick={onClose} style={{ background: "none", border: "1px solid #E8E6E1", borderRadius: 6, padding: "5px 12px", fontSize: 12, color: "#6E6E73", cursor: "pointer" }}>Close</button>
      </div>

      {guide === null && loading === false && (
        <div style={{ textAlign: "center", padding: "32px 20px", background: "#f5f3ef", borderRadius: 12, border: "1px solid #E8E6E1" }}>
          <div style={{ fontSize: 15, fontWeight: 600, color: "#1C1C1E", marginBottom: 6 }}>Ready to generate your study guide</div>
          <div style={{ fontSize: 13, color: "#6E6E73", marginBottom: 20, lineHeight: 1.6 }}>Gemma 4 will read your document and create key concepts, practice questions, and memory tricks.</div>
          <button onClick={generate} style={{ background: "#3d3428", color: "#F2F0EB", border: "none", borderRadius: 8, padding: "12px 28px", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "system-ui, sans-serif" }}>
            Generate Study Guide
          </button>
        </div>
      )}

      {loading === true && (
        <div style={{ textAlign: "center", padding: "40px 20px" }}>
          <div style={{ fontSize: 13, color: "#6E6E73", marginBottom: 16 }}>Gemma 4 is reading your document...</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {[100, 85, 92, 78, 88].map(function(w, i) {
              return <div key={i} className="skeleton" style={{ width: w + "%", height: 14, borderRadius: 6 }} />;
            })}
          </div>
        </div>
      )}

      {error.length > 0 && (
        <div style={{ padding: "12px 14px", background: "#FFF0F0", border: "1px solid #FFCDD2", borderRadius: 8, fontSize: 13, color: "#C62828" }}>{error}</div>
      )}

      {guide !== null && (
        <div id="qt-study-content">
          <Section title="Key Concepts" items={guide.concepts} color="#3d3428" />
          <Section title="Practice Questions" items={guide.questions} color="#a88f6b" />
          <Section title="Memory Tricks" items={guide.tricks} color="#10b981" />
          <div style={{ display: "flex", gap: 10, marginTop: 8 }}>
            <button onClick={handlePrint} style={{ background: "#1C1C1E", color: "#F2F0EB", border: "none", borderRadius: 8, padding: "10px 20px", fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "system-ui, sans-serif" }}>
              {printed ? "Printed" : "Print Study Guide"}
            </button>
            <button onClick={generate} style={{ background: "transparent", border: "1px solid #E8E6E1", borderRadius: 8, padding: "10px 20px", fontSize: 13, color: "#6E6E73", cursor: "pointer", fontFamily: "system-ui, sans-serif" }}>
              Regenerate
            </button>
          </div>
        </div>
      )}
    </div>
  );
}